# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install pytest-cov
            pip install -r requirements.txt
            python -m pytest --version
            pip install codecov


    # testing
      - name: Test with pytest
        run: |
            python -m pytest tests/test1.py
            python -m pytest tests/test2.py
            python -m pytest tests/test3.py
            python -m pytest tests/test4.py
            python -m pytest tests/test5.py

    # code coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}

      - name: Get coverage
        run: |
            python -m coverage
            python -m codecov
