# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install flake8
            pip install pytest
            pip install pytest-cov
            pip install -r requirements.txt
            pip install codecov


    # testing with pytest, generate coverage report
      - name: Test with pytest and generate coverage xml
        run: |
            python -m pytest test

            python -m coverage run test/test_1.py
            python -m coverage run test/test_2.py
            python -m coverage run test/test_3.py
            python -m coverage run test/test_4.py
            python -m coverage run test/test_5.py
            python -m coverage run test/test_6.py
            python -m coverage run test/test_7.py

            python -m coverage xml

    # Upload code coverage to codecov
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

    # Linting step
      - name: Lint source code with flake8
        run: python -m flake8 src/
